# Mecánica Celeste: teoría, algoritmos y problemas
## Por Jorge I. Zuluaga

### Primeros pasos con `pymcel`
<a target="_blank" href="https://colab.research.google.com/github/seap-udea/pymcel/blob/main/ejemplos/pymcel-primeros-pasos.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

#### Ejecutar antes de comenzar

Si estas usando este ejemplo en `Google Colab` debes ejecutar esta celda:

In [8]:
import sys
if 'google.colab' in sys.modules:
    !sudo pip install -Uq pymcel

### Importando `pymcel`

Para empezar a usar el paquete es necesario importarlo:

In [1]:
import pymcel as pc
%load_ext autoreload 
%autoreload 2

pymcel version  0.6.25


> **NOTA**: Los *comandos mágicos* `%load_ext` y `%autoreload` solo son necesarios durante la fase de desarrollo. Puedes obviarlos en tus propios cuadernos.

### Variables incorporadas en el paquete

El paquete puede venir con una serie de variables incorporadas cuyo valor puedes ver haciendo:

In [2]:
pc.version

'0.6.25'

En general las variables globales incluídas en el paquete se escriben en mayúscula sostenida. Por ejemplo, la variable `ROOTDIR` muestra donde se encuentran instalados los archivos del paquete en el sistema:

In [3]:
pc.ROOTDIR

'/Users/jzuluaga/dev/pymcel/src/pymcel'

### Constantes incluídas en el paquete

El paquete viene con algunas constantes físicas y astronómicas de interés. Por ejemplo:

In [4]:
pc.constantes.G, pc.constantes.au

(np.float64(6.6743e-11), np.float64(149597870700.0))

Todas las constantes están en el sistema internacional de unidades.

Para ver una lista completa de constantes usar:

In [5]:
print(pc.constantes.lista)

['G', 'N_A', 'R', 'Ryd', 'a0', 'alpha', 'atm', 'b_wien', 'c', 'e', 'eps0', 'g0', 'h', 'hbar', 'k_B', 'm_e', 'm_n', 'm_p', 'mu0', 'muB', 'sigma_T', 'sigma_sb', 'u', 'GM_earth', 'GM_jup', 'GM_sun', 'L_bol0', 'L_sun', 'M_earth', 'M_jup', 'M_sun', 'R_earth', 'R_jup', 'R_sun', 'au', 'kpc', 'pc', 'año', 'día', 'mu_mercury', 'mu_venus', 'mu_earth', 'mu_emb', 'mu_mars', 'mu_jupiter', 'mu_saturn', 'mu_uranus', 'mu_neptune', 'mu_pluto', 'mu_sun', 'mu_moon']


La mayoría de estas constantes vienen originalmente del paquete `astropy` de modo que su significado puede buscarse en la documentación de ese paquete.

In [2]:
pc.constantes?

Type:        module
String form: <module 'pymcel.constantes' from '/Users/jzuluaga/dev/pymcel/src/pymcel/constantes.py'>
File:        ~/dev/pymcel/src/pymcel/constantes.py
Docstring:  
Constantes físicas y astronómicas.

Notas:

- Todas las constantes están en unidades SI.
- Las constantes de astropy están en unidades SI, pero se pueden convertir a otras unidades usando la función
    astropy.constants.convert.
- Las constantes de astropy están en el módulo astropy.constants.
- Los parámetros gravitacionales vienen del kernel SPICE DE441.

In [4]:
tabla, tiempos, matriz = pc.consulta_horizons(
    id='399',
    location='@0',
    epochs='2025-01-01 12:00:00'
)
matriz, tiempos

(array([-2.88732390e+10,  1.43679159e+11,  1.92000567e+07, -2.97269012e+04,
        -5.79739787e+03, -2.94835140e-01]),
 np.float64(2460677.0))

In [6]:
pc.prepara_spice()

Cargando todos los kernels de SPICE...
El entorno está listo para usar los datos de SPICE.


In [11]:
tabla, tiempos, matriz = pc.consulta_spice(
    id='399',
    location='@0',
    epochs='2025-01-01 12:00:00'
)
matriz, tiempos

pymcel version  0.6.25


(array([-2.88731332e+10,  1.43679205e+11,  1.91885691e+07, -2.97269012e+04,
        -5.79739790e+03, -2.94814107e-01]),
 array([2460677.]))

<hr/>

Para explorar más ejemplos vaya al repositorio de [`pymcel` en GitHub](https://github.com/seap-udea/pymcel/tree/main/ejemplos)